version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'cookies_shop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data-volume:/var/lib/mysql
  cookies_shop:
    container_name: cookies_shop
    restart: unless-stopped
    image: cookies_shop
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    ports:
      - '80:80'
# Names our volume
volumes:
  mysql-data-volume: null
